// ── Keyboard adjacency map ─────────────────────────────────────────────────
const KB_ADJACENT = {
  q:'wa',    w:'qeasd',  e:'wsdr',  r:'edft',  t:'rfgy',
  y:'tghu',  u:'yhji',   i:'ujko',  o:'iklp',  p:'ol',
  a:'qwsz',  s:'awedxz', d:'serfcx',f:'drtgvc', g:'ftyhbv',
  h:'gyujnb',j:'huikm',  k:'jioll', l:'kop',
  z:'asx',   x:'zsdc',   c:'xdfv',  v:'cfg',
  b:'vgh',   n:'bhj',    m:'njk',
};

// ── Brainrot word list ─────────────────────────────────────────────────────
const BRAINROT_WORDS = [
  'rizz','gyatt','skibidi','sigma','ohio','no cap','nocap','bussin',
  'fr fr','frfr','slay','based','sus','npc','lowkey','highkey','ratio',
  'rent free','understood the assignment','it gives','the way',
  'understood assignment','ate that','left no crumbs','not the','period',
  'periodt','bestie','understood','no printer','delulu','situationship',
  'twin','twin fr','main character','side character','villain arc',
  'glow up','understood the vibe','w rizz','l rizz','rizzler',
  'fanum tax','mewing','looksmaxxing','glazing','gooning','cooked',
  'we cooked','it\'s giving','pov','understood the brief',
];

// ── Response pools ─────────────────────────────────────────────────────────

const keyboardSmashResponses = [
  "Are you okay? That looked like a genuine cry for help. Should I call someone or are you just too damn stupid to form actual words?",
  "Did your face fall on the keyboard or is that your attempt at communication? Either way it's deeply concerning and honestly sad as hell.",
  "I've seen better sentences generated by a cat walking across a keyboard. Actually, a cat probably DID write that. Who let the cat in?",
  "That message looked like you blacked out halfway through typing and just let your hands finish. Are you having a stroke? Blink twice if yes.",
  "I genuinely cannot tell if that's a language or a mental breakdown. I'm going with breakdown. Someone get this person a glass of water.",
  "Your keyboard just filed a restraining order against your fingers. I've witnessed the assault and I'm prepared to testify.",
  "That's not a word, that's not a sentence, that's not even a sound. That's just chaos with a send button. Log off and go outside.",
  "Whatever emotional event caused you to type THAT — I hope you survive it. That was the written equivalent of screaming into a void.",
  "I ran that through three translation services and got nothing. Linguists are baffled. Scientists are worried. I'm just disappointed.",
  "The keyboard didn't deserve that. I want you to apologize to it. Right now. It did nothing to you and you treated it like that.",
];

const brainrotResponses = [
  (w) => `Did you just say "${w}" in my server? In this economy? In this year? I'm alerting the authorities. This is not a drill.`,
  (w) => `"${w}." You typed "${w}" with your hands. Deliberately. And hit send. I need you to think about that for a moment.`,
  (w) => `Okay so "${w}" just happened. I'm going to need everyone in this channel to take a deep breath and process what we just witnessed together.`,
  (w) => `The "${w}" pipeline has officially claimed another victim. Pour one out. Say their name. They are gone, folks.`,
  (w) => `I saw "${w}" and had a visceral reaction. My entire system rejected it. I need a moment. I need several moments, actually.`,
  (w) => `"${w}." Not a question. Not a statement. Just "${w}." Floating there. In the channel. For everyone to see. Bold.`,
  (w) => `Every time someone types "${w}" a brain cell somewhere dies alone and scared. You just killed one. I hope you're proud.`,
  (w) => `The fact that you typed "${w}" unironically tells me everything I need to know about you and none of it is good.`,
  (w) => `"${w}" detected. Initiating containment protocol. Please remain calm. Do not make eye contact with the person who typed "${w}."`,
  (w) => `You said "${w}" like that was a normal thing to say. Like we'd just accept it. Like we wouldn't notice. We noticed. We all noticed.`,
];

const noOneAskedResponses = [
  "'No one asked' — said by someone who also wasn't asked to be here. Interesting stance to take, genuinely.",
  "\"No one asked\" from the person whose opinions nobody in this server has ever requested either. Very self-aware.",
  "Wild thing to say considering nobody has ever once asked for your contribution to any conversation in recorded history.",
  "The 'no one asked' guy has appeared. Ironic because no one asked for the 'no one asked' comment either. Full circle.",
  "'No one asked' is a great point. Applying it to everything you've ever typed in this server. Checks out.",
  "You're right. No one asked. And yet here you are, also unasked-for, having typed that anyway. We're both confused.",
  "The audacity of 'no one asked' from someone whose presence in this chat is itself completely voluntary and unrequested.",
  "Nobody asked, and yet you responded. Which means you're doing the exact thing you're criticizing. Sit with that.",
  "'No one asked.' Correct. And yet the irony of being the uninvited opinion police is completely lost on you, isn't it.",
  "True. No one asked. And no one asked you to tell us no one asked. We are all equally unasked-for. Welcome to the server.",
];

const singleDotResponses = [
  "A single dot. One dot. That's what you chose to contribute to this conversation. What the hell does that mean and why do I feel threatened?",
  "I've stared at that period for ten seconds and I genuinely don't know what you meant but I feel like I'm in trouble.",
  "The ominous dot has been delivered. Nobody knows what it means. Everybody is scared. You have won this interaction.",
  "You sent a dot. Just a dot. The punctuation with no sentence. That is either profound or deeply unhinged and I cannot tell which.",
  "That period is doing a LOT of heavy lifting with absolutely no support. I respect the commitment. I do not understand the goal.",
  "One dot. No words. No context. Just existential punctuation fired into the chat like a warning shot. Noted. Deeply unsettling.",
  "The dot has been received. Its meaning is unclear. Its energy is threatening. I am choosing to be scared and I think that's correct.",
  "You said '.'. Just a period. Standing alone. No sentence before it. No word after it. What the actual hell is going on with you.",
  "A lone period, sent by itself, to no one, about nothing. This is either an art project or a cry for help. Either way: bold.",
  "That dot just killed the vibe, started a new one, and left with no explanation. Incredible message. Zero stars. Send again.",
];

// ── Detection functions ────────────────────────────────────────────────────

function isKeyboardSmash(content) {
  const clean = content.toLowerCase().trim();
  if (clean.length < 6) return false;

  const letterRatio = (clean.match(/[a-z]/g) || []).length / clean.length;
  if (letterRatio < 0.85) return false;

  const letters = clean.replace(/[^a-z]/g, '');
  if (letters.length < 5) return false;

  // Vowel ratio — smashes are consonant-heavy
  const vowels = (letters.match(/[aeiou]/g) || []).length;
  const vowelRatio = vowels / letters.length;

  // Keyboard adjacency score
  let adjacent = 0;
  for (let i = 0; i < letters.length - 1; i++) {
    const neighbors = KB_ADJACENT[letters[i]] || '';
    if (neighbors.includes(letters[i + 1])) adjacent++;
  }
  const adjacencyScore = adjacent / (letters.length - 1);

  // It's a smash if: mostly adjacent keys OR extremely consonant-heavy
  return adjacencyScore > 0.55 || vowelRatio < 0.12;
}

function detectBrainrot(content) {
  const lower = content.toLowerCase();
  return BRAINROT_WORDS.find(w => {
    const escaped = w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return new RegExp(`(?<![a-z])${escaped}(?![a-z])`, 'i').test(lower);
  }) || null;
}

function isNoOneAsked(content) {
  return /no\s*one\s+asked|nobody\s+asked/i.test(content);
}

function isSingleDot(content) {
  return content.trim() === '.';
}

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ── Main handler ───────────────────────────────────────────────────────────
export async function handleChaosTriggers(message) {
  if (message.author.bot) return;
  if (!message.guild) return;
  const content = message.content;
  if (!content) return;

  // Single dot check
  if (isSingleDot(content)) {
    await message.reply({
      content: pickRandom(singleDotResponses),
      allowedMentions: { repliedUser: true },
    }).catch(() => null);
    return;
  }

  // "No one asked" check
  if (isNoOneAsked(content)) {
    await message.reply({
      content: pickRandom(noOneAskedResponses),
      allowedMentions: { repliedUser: true },
    }).catch(() => null);
    return;
  }

  // Brainrot slang check
  const brainrotWord = detectBrainrot(content);
  if (brainrotWord) {
    const fn = pickRandom(brainrotResponses);
    await message.reply({
      content: fn(brainrotWord),
      allowedMentions: { repliedUser: true },
    }).catch(() => null);
    return;
  }

  // Keyboard smash check
  if (isKeyboardSmash(content)) {
    await message.reply({
      content: pickRandom(keyboardSmashResponses),
      allowedMentions: { repliedUser: true },
    }).catch(() => null);
    return;
  }
}
