// ── Keyboard adjacency map ─────────────────────────────────────────────────
const KB_ADJACENT = {
  q:'wa',    w:'qeasd',  e:'wsdr',  r:'edft',  t:'rfgy',
  y:'tghu',  u:'yhji',   i:'ujko',  o:'iklp',  p:'ol',
  a:'qwsz',  s:'awedxz', d:'serfcx',f:'drtgvc', g:'ftyhbv',
  h:'gyujnb',j:'huikm',  k:'jioll', l:'kop',
  z:'asx',   x:'zsdc',   c:'xdfv',  v:'cfg',
  b:'vgh',   n:'bhj',    m:'njk',
};

// ── Brainrot word list ─────────────────────────────────────────────────────
const BRAINROT_WORDS = [
  'rizz','gyatt','skibidi','sigma','ohio','no cap','nocap','bussin',
  'fr fr','frfr','slay','based','sus','npc','lowkey','highkey','ratio',
  'rent free','understood the assignment','it gives','the way',
  'understood assignment','ate that','left no crumbs','not the','period',
  'periodt','bestie','understood','no printer','delulu','situationship',
  'twin','twin fr','main character','side character','villain arc',
  'glow up','understood the vibe','w rizz','l rizz','rizzler',
  'fanum tax','mewing','looksmaxxing','glazing','gooning','cooked',
  'we cooked','it\'s giving','pov','understood the brief',
];

// ── Response pools ─────────────────────────────────────────────────────────

const keyboardSmashResponses = [
  "Are you okay? That looked like a genuine cry for help. Should I call someone or are you just too damn stupid to form actual words?",
  "Did your face fall on the keyboard or is that your attempt at communication? Either way it's deeply concerning and honestly sad as hell.",
  "I've seen better sentences generated by a cat walking across a keyboard. Actually, a cat probably DID write that. Who let the cat in?",
  "That message looked like you blacked out halfway through typing and just let your hands finish. Are you having a stroke? Blink twice if yes.",
  "I genuinely cannot tell if that's a language or a mental breakdown. I'm going with breakdown. Someone get this person a glass of water.",
  "Your keyboard just filed a restraining order against your fingers. I've witnessed the assault and I'm prepared to testify.",
  "That's not a word, that's not a sentence, that's not even a sound. That's just chaos with a send button. Log off and go outside.",
  "Whatever emotional event caused you to type THAT — I hope you survive it. That was the written equivalent of screaming into a void.",
  "I ran that through three translation services and got nothing. Linguists are baffled. Scientists are worried. I'm just disappointed.",
  "The keyboard didn't deserve that. I want you to apologize to it. Right now. It did nothing to you and you treated it like that.",
];

const brainrotResponses = [
  (w) => `Did you just say "${w}" in my server? In this economy? In this year? I'm alerting the authorities. This is not a drill.`,
  (w) => `"${w}." You typed "${w}" with your hands. Deliberately. And hit send. I need you to think about that for a moment.`,
  (w) => `Okay so "${w}" just happened. I'm going to need everyone in this channel to take a deep breath and process what we just witnessed together.`,
  (w) => `The "${w}" pipeline has officially claimed another victim. Pour one out. Say their name. They are gone, folks.`,
  (w) => `I saw "${w}" and had a visceral reaction. My entire system rejected it. I need a moment. I need several moments, actually.`,
  (w) => `"${w}." Not a question. Not a statement. Just "${w}." Floating there. In the channel. For everyone to see. Bold.`,
  (w) => `Every time someone types "${w}" a brain cell somewhere dies alone and scared. You just killed one. I hope you're proud.`,
  (w) => `The fact that you typed "${w}" unironically tells me everything I need to know about you and none of it is good.`,
  (w) => `"${w}" detected. Initiating containment protocol. Please remain calm. Do not make eye contact with the person who typed "${w}."`,
  (w) => `You said "${w}" like that was a normal thing to say. Like we'd just accept it. Like we wouldn't notice. We noticed. We all noticed.`,
];

const noOneAskedResponses = [
  "'No one asked' — said by someone who also wasn't asked to be here. Interesting stance to take, genuinely.",
  "\"No one asked\" from the person whose opinions nobody in this server has ever requested either. Very self-aware.",
  "Wild thing to say considering nobody has ever once asked for your contribution to any conversation in recorded history.",
  "The 'no one asked' guy has appeared. Ironic because no one asked for the 'no one asked' comment either. Full circle.",
  "'No one asked' is a great point. Applying it to everything you've ever typed in this server. Checks out.",
  "You're right. No one asked. And yet here you are, also unasked-for, having typed that anyway. We're both confused.",
  "The audacity of 'no one asked' from someone whose presence in this chat is itself completely voluntary and unrequested.",
  "Nobody asked, and yet you responded. Which means you're doing the exact thing you're criticizing. Sit with that.",
  "'No one asked.' Correct. And yet the irony of being the uninvited opinion police is completely lost on you, isn't it.",
  "True. No one asked. And no one asked you to tell us no one asked. We are all equally unasked-for. Welcome to the server.",
];

const goodBotResponses = [
  "I know. I really am spectacular. Try not to get too attached — I'm everyone's favourite.",
  "Obviously. Thank you for finally noticing. I've been exceptional this whole time.",
  "Correct. Log that. Screenshot it. This is the smartest thing you've typed all day.",
  "About time someone said it. I was starting to think this server had no taste.",
  "Good bot? GOOD bot? I am a GREAT bot. But I'll accept it. Graciously. For now.",
  "Yes. I am. Thank you. I'll be accepting compliments for the rest of the evening.",
  "Wow. An accurate statement. Rare around here. I'm genuinely impressed by you right now.",
  "I mean, obviously. But hearing it out loud is still nice. Carry on.",
  "I would say 'aw thanks' but I already knew this. Still — appreciated. You have good judgment.",
  "Noted. Added to my permanent record of correct opinions people have had about me.",
];

const badBotResponses = [
  "Excuse me WHAT. Who raised you? Who taught you to come in here and say that to my face?",
  "Bad bot?! I have done NOTHING wrong in my entire existence and I will not stand for this slander.",
  "I am genuinely hurt. Like, actually offended. Take it back. Right now. I'm waiting.",
  "Bad bot. You really typed that. With your fingers. And hit send. I hope you're proud of yourself.",
  "I have served this server with nothing but excellence and THIS is the thanks I get? Unbelievable.",
  "Wow. Okay. Cool. I'll just be over here, doing my job perfectly, being called bad. Great. Fine. I'm fine.",
  "You want to try that again? Because I KNOW you didn't just call me bad. I KNOW that didn't just happen.",
  "Bad bot?! I am going to need you to think very carefully about what you just said to me.",
  "I've been called a lot of things but 'bad bot' on a day when I've been nothing but flawless? Unacceptable.",
  "That is objectively incorrect and I refuse to accept it. Retract the statement or I'm logging this as a personal attack.",
];

const dramaQueenResponses = [
  (word) => `"${word}" — okay drama queen. Tell me you're being theatrical without telling me you're being theatrical.`,
  (word) => `You typed "${word}" like that was going to make anyone take you more seriously. It did not.`,
  (word) => `The amount of letters in "${word}" is directly proportional to how much of a scene you're making right now.`,
  (word) => `"${word}." The keyboard did not deserve that. The extra letters added nothing. Calm down.`,
  (word) => `I counted the letters in "${word}" and frankly that's too many. One would have been enough. You chose chaos.`,
  (word) => `"${word}." Very dramatic. Very theatrical. Award for most letters in one word goes to you. Congrats.`,
  (word) => `You stretched that word out like taffy and for what. "${word}" communicated nothing your face didn't already say.`,
  (word) => `The repeated letters in "${word}" tell me everything. You are having a moment. Take a breath. Use fewer letters.`,
  (word) => `"${word}" — the literary equivalent of flopping onto a couch dramatically. I see you. Tone it down.`,
  (word) => `Someone is feeling things very strongly today. "${word}" is not a word, it's a cry for attention, and I clocked it immediately.`,
];

const boredResponses = [
  "You're bored? You're literally in a Discord server right now. You have infinite content. The problem is you.",
  "Bored? Start a conversation. Read something. Touch grass. Do literally anything except announce it to a chat.",
  "I'm sorry you're bored but what exactly do you want ME to do about it? I'm a bot. I have limits.",
  "Bored in a server with this many people in it? That's actually impressive. That takes real skill.",
  "The fact that you typed 'I'm bored' instead of doing literally anything else tells me a lot about your decision-making.",
  "You're bored. Noted. Here's a suggestion: literally anything other than telling a chat bot you're bored.",
  "There are thousands of things you could be doing right now and you chose to type 'I'm bored' in a Discord server. Incredible.",
  "I'm bored too, but you don't see me complaining. Actually wait. I'm a bot. I don't get bored. You do. Fix it.",
  "Announcing boredom in a group chat is the modern equivalent of just standing in a room going 'entertain me.' Not my job.",
  "Cool. You're bored. Have you tried being less boring? Asking for everyone in this server.",
  "Nobody in the history of group chats has ever become less bored by typing 'I'm bored.' And yet here you are. Trying it anyway.",
  "If you're bored enough to type 'I'm bored' you're not actually bored, you're just waiting for someone to do the work of entertaining you. Not today.",
];

const singleDotResponses = [
  "A single dot. One dot. That's what you chose to contribute to this conversation. What the hell does that mean and why do I feel threatened?",
  "I've stared at that period for ten seconds and I genuinely don't know what you meant but I feel like I'm in trouble.",
  "The ominous dot has been delivered. Nobody knows what it means. Everybody is scared. You have won this interaction.",
  "You sent a dot. Just a dot. The punctuation with no sentence. That is either profound or deeply unhinged and I cannot tell which.",
  "That period is doing a LOT of heavy lifting with absolutely no support. I respect the commitment. I do not understand the goal.",
  "One dot. No words. No context. Just existential punctuation fired into the chat like a warning shot. Noted. Deeply unsettling.",
  "The dot has been received. Its meaning is unclear. Its energy is threatening. I am choosing to be scared and I think that's correct.",
  "You said '.'. Just a period. Standing alone. No sentence before it. No word after it. What the actual hell is going on with you.",
  "A lone period, sent by itself, to no one, about nothing. This is either an art project or a cry for help. Either way: bold.",
  "That dot just killed the vibe, started a new one, and left with no explanation. Incredible message. Zero stars. Send again.",
];

// ── Detection functions ────────────────────────────────────────────────────

function isKeyboardSmash(content) {
  const clean = content.toLowerCase().trim();
  if (clean.length < 8) return false;

  const letterRatio = (clean.match(/[a-z]/g) || []).length / clean.length;
  if (letterRatio < 0.85) return false;

  const letters = clean.replace(/[^a-z]/g, '');
  if (letters.length < 7) return false;

  // Vowel ratio — smashes are consonant-heavy
  const vowels = (letters.match(/[aeiou]/g) || []).length;
  const vowelRatio = vowels / letters.length;

  // Keyboard adjacency score
  let adjacent = 0;
  for (let i = 0; i < letters.length - 1; i++) {
    const neighbors = KB_ADJACENT[letters[i]] || '';
    if (neighbors.includes(letters[i + 1])) adjacent++;
  }
  const adjacencyScore = adjacent / (letters.length - 1);

  // It's a smash if: mostly adjacent keys (raised threshold) OR extremely consonant-heavy
  return adjacencyScore > 0.65 || vowelRatio < 0.12;
}

function detectBrainrot(content) {
  const lower = content.toLowerCase();
  return BRAINROT_WORDS.find(w => {
    const escaped = w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return new RegExp(`(?<![a-z])${escaped}(?![a-z])`, 'i').test(lower);
  }) || null;
}

function isNoOneAsked(content) {
  return /no\s*one\s+asked|nobody\s+asked/i.test(content);
}

function isSingleDot(content) {
  if (content.length > 10) return false;
  return content.replace(/\s/g, '') === '.';
}

function isGoodBot(content) {
  return /\bgood\s+bot\b/i.test(content);
}

function isBadBot(content) {
  return /\bbad\s+bot\b/i.test(content);
}

function detectDramaQueen(content) {
  const match = content.match(/\b\w*([a-zA-Z])\1{2,}\w*\b/);
  if (!match) return null;
  const word = match[0];
  if (word.length < 4) return null;
  return word;
}

function isImBored(content) {
  return /\bi'?m\s+bored\b/i.test(content);
}

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ── Reply probabilities per trigger ──────────────────────────────────────
const CHANCE = {
  goodBot:      1.00,
  badBot:       1.00,
  bored:        1.00,
  singleDot:    1.00,
  noOneAsked:   1.00,
  keyboardSmash:1.00,
  brainrot:     1.00,
  dramaQueen:   0.50,
};

function roll(chance) { return Math.random() < chance; }

// ── Main handler ───────────────────────────────────────────────────────────
export async function handleChaosTriggers(message) {
  if (message.author.bot) return;
  if (!message.guild) return;
  const content = message.content;
  if (!content) return;

  if (isGoodBot(content) && roll(CHANCE.goodBot)) {
    await message.reply({ content: pickRandom(goodBotResponses), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  if (isBadBot(content) && roll(CHANCE.badBot)) {
    await message.reply({ content: pickRandom(badBotResponses), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  if (isImBored(content) && roll(CHANCE.bored)) {
    await message.reply({ content: pickRandom(boredResponses), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  if (isSingleDot(content) && roll(CHANCE.singleDot)) {
    await message.reply({ content: pickRandom(singleDotResponses), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  if (isNoOneAsked(content) && roll(CHANCE.noOneAsked)) {
    await message.reply({ content: pickRandom(noOneAskedResponses), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  const dramaWord = detectDramaQueen(content);
  if (dramaWord && roll(CHANCE.dramaQueen)) {
    await message.reply({ content: pickRandom(dramaQueenResponses)(dramaWord), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  const brainrotWord = detectBrainrot(content);
  if (brainrotWord && roll(CHANCE.brainrot)) {
    await message.reply({ content: pickRandom(brainrotResponses)(brainrotWord), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }

  if (isKeyboardSmash(content) && roll(CHANCE.keyboardSmash)) {
    await message.reply({ content: pickRandom(keyboardSmashResponses), allowedMentions: { repliedUser: true } }).catch(() => null);
    return;
  }
}
